#!/usr/bin/python2
#coding: utf-8
import sys
import os
import gtk, pygtk
import shout
import time
from mutagen.easyid3 import EasyID3
import source
import getopt

def daemonize(stdin = '/dev/null', stdout = '/dev/null', stderr='/dev/null'):
    try:
        pid = os.fork()
        if pid>0:
            sys.exit(0)
    except OSError, e:
        sys.stderr.write ("fork #1 failed: (%d) %s\n" % (e.errno, e.strerror) )
        sys.exit(1)

    os.chdir('/')
    os.umask(0)
    os.setsid()

    try:
        pid = os.fork()
        if pid>0:
            sys.exit(0)
    except OSError, e:
        sys.stderr.write ("fork #2 failed: (%d) %s\n" % (e.errno, e.strerror) )
        sys.exit(1)

    si = open(stdin, 'r')
    so = open(stdout, 'a+')
    se = open(stderr, 'a+', 0)

    os.dup2(si.fileno(), sys.stdin.fileno())
    os.dup2(so.fileno(), sys.stdout.fileno())
    os.dup2(se.fileno(), sys.stderr.fileno())

opts, args = getopt.getopt(sys.argv[1:], 'dm=M', ['daemon', 'mount='])
opts = opts[0]

print opts, args

mount = '/rockHQ'

for n in range(len(opts)):
    opt = opts[n]
    if opt in ('-m', '--mount'):
        mount = args[n]
    elif opt== '-d':
        daemonize('/dev/null', '/tmp/source.log', '/tmp/source.log')


S = source.Source(u'/media/d/Music', mount)

try:
    while 1:
        time.sleep(1)
except:
    S.stop()
